---
name: CI

on:
  push:
    branches: [master]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running YAMLlint
        uses: 'docker://pipelinecomponents/yamllint:latest'
        with:
          args: yamllint .
